### ISSUE TITLE
OutOfMemoryError in "Server"

### ISSUE THREAD

**Issue by scopeInfinity** [scopeInfinity/DivvyHost#4]
On multiple Connection to Server again and again

```
Exception in thread "Server" java.lang.OutOfMemoryError: Java heap space
at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
at com.esotericsoftware.kryonet.TcpConnection.<init>(TcpConnection.java:35)
at com.esotericsoftware.kryonet.Connection.initialize(Connection.java:39)
at com.esotericsoftware.kryonet.Server.acceptOperation(Server.java:378)
at com.esotericsoftware.kryonet.Server.update(Server.java:242)
at com.esotericsoftware.kryonet.Server.run(Server.java:356)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by scopeInfinity** [comment]
Fixed by b88622f471154df2dd817c43e384f75070edf000 commit
Used _java.rmi_ instead of _kryonet_.
